[tool.poetry]
name = "microcurrency"
version = "1.0.3"
description = ""
authors = ["BadPythonCoder <nuh@uh.uh>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
discord-py = "^2.3.1"
fastapi = "^0.109.0"
uvicorn = "^0.27.0.post1"
json5 = "^0.10.0"
requests = "^2.32.3"
sqlmodel = "^0.0.22"

[tool.poetry.scripts]
bot = "microcurrency.__init__:start"
create_currency = "microcurrency.scripts:create_curr"
create_transaction = "microcurrency.scripts:create_transaction"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
