class TRANSACTION_RESPONSES:
	SUCCESS = 0
	NEGATIVE_AMOUNT = 1
	SELF_SEND = 2
	INSUFFICIENT_FUNDS = 3

class EXCHANGE_RESPONSES:
	SUCCESS = 0
	CURRENCYA_IS_CURRENCYB = 1
	TRANSACTION_FAILED_ON_BOTS_END = 2
	NEGATIVE_AMOUNT = 3
	INSUFFICIENT_FUNDS = 4 

EXCHANGE_TRANSACTION_MAP = { # This is absolutely terrible, TODO: **REDO THE ENUMS**
	TRANSACTION_RESPONSES.NEGATIVE_AMOUNT: EXCHANGE_RESPONSES.NEGATIVE_AMOUNT,
	TRANSACTION_RESPONSES.INSUFFICIENT_FUNDS: EXCHANGE_RESPONSES.INSUFFICIENT_FUNDS
}