class TRANSACTION_RESPONSES:
	SUCCESS = 0
	NEGATIVE_AMOUNT = 1
	SELF_SEND = 2
	INSUFFICIENT_FUNDS = 3

class EXCHANGE_RESPONSES:
	SUCCESS = 0
	EXCHANGING_STANDARD_FOR_STANDARD = 1
	TRANSACTION_FAILED_ON_USERS_END = 2
	TRANSACTION_FAILED_ON_BOTS_END = 3